language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.10"
  - "0.8"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpoppler-cpp-dev libpoppler-dev libfontconfig1-dev libpng12-dev libjpeg-turbo8-dev libtiff4-dev
